format = """
[](#000000)\
$username\
[](bg:#ad0000 fg:#000000)\
$directory\
[](fg:#ad0000 bg:#ffffff)\
$git_branch\
$git_status\    
[](fg:#ffffff bg:#efef00)\
$time\
[ ](fg:#efef00)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#000000"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#ad0000"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Desktop" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#ffffff"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ffffff"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#efef00"
format = '[ 醴 $time ]($style)'
